### ISSUE TITLE
[Bug]: Invalid pest command

### ISSUE THREAD

**Issue by edalzell** [laravel/vs-code-extension#167]
### Extension Version

0.1.15

### PHP Binary

Herd

### Operating System

macOS

### What happened?

I get this error all the time when I open a php file.

```
2025-01-07 09:50:09.528 [info] Activating Laravel Extension...
2025-01-07 09:50:09.528 [info] Started
2025-01-07 09:50:12.001 [error] Error:
 Eloquent Attributes and Relations

__VSCODE_LARAVEL_START_OUTPUT__
   Pest\Exceptions\InvalidPestCommand 

  Please run [./vendor/bin/pest] instead.


2025-01-07 09:50:12.001 [error] /Users/erin/Library/Application\ Support/Herd/bin/php /Users/erin/Sites/glazed/vendor/_laravel_ide/discover-5ea4ce032fd4176b9750a211674781fa.php
2025-01-07 09:50:12.001 [error] Eloquent Attributes and Relations

__VSCODE_LARAVEL_START_OUTPUT__
   Pest\Exceptions\InvalidPestCommand 

  Please run [./vendor/bin/pest] instead.


```

**Comment by joetannenbaum** [comment]
This one is pretty weird, no idea how it's getting to Pest...

I'm curious: If you run `php artisan model:show [name of any of your models] --json` does this error show up?

**Comment by edalzell** [comment]
Nope, but I do have the Better PHPUnit from Caleb installed, maybe that's something?

**Comment by jtomek** [comment]
Regarding the pest error, I fixed it in my setting.
I used to have {Class}.Test.php files in my app/Models folder. I like to have tests next to my classes (colored) so I can easily see which ones have tests and which ones don't.
I moved the tests from the app/Models folder to /test/...  and it all works.

Regarding "Eloquent Attributes and Relations" ... I am debugging the extension now...

**Comment by edalzell** [comment]
I'm still getting this, on L12, latest extension version:


```
2025-03-01 11:28:57.630 [info] Checking herd PHP installation: herd which-php
2025-03-01 11:28:57.630 [info] Using herd PHP installation: /Users/erin/Library/Application Support/Herd/bin/php84
2025-03-01 11:28:57.630 [info] Activating Laravel Extension...
2025-03-01 11:28:57.630 [info] Started
2025-03-01 11:28:58.517 [error] Auth Data

Error: __VSCODE_LARAVEL_START_OUTPUT__
   Pest\Exceptions\InvalidPestCommand 

  Please run [./vendor/bin/pest] instead.


2025-03-01 11:28:58.517 [error] Eloquent Attributes and Relations

Error: __VSCODE_LARAVEL_START_OUTPUT__
   Pest\Exceptions\InvalidPestCommand 

  Please run [./vendor/bin/pest] instead.
```

All I'm doing is opening a PHP file. Wonder if it's the Better PHPUnit extension

**Comment by depsimon** [comment]
I also experience this issue while opening a PHP file.

```sh
2025-03-09 09:53:10.276 [error] Eloquent Attributes and Relations

Error: __VSCODE_LARAVEL_START_OUTPUT__
   Pest\Exceptions\InvalidPestCommand 

  Please run [./vendor/bin/pest] instead.
```

**Comment by TitasGailius** [comment]
Thanks for reporting this. We’re clearing out some older issues that may have been fixed by the latest improvements in the extension. Feel free to reopen if you’re still experiencing anything similar.
