### ISSUE TITLE
[Bug]: "[error] Translation namespaces"

### ISSUE THREAD

**Issue by Jipem** [laravel/vs-code-extension#212]
### Extension Version

0.1.18

### PHP Binary

Local PHP

### Operating System

Windows

### What happened?

On start of Visual Studio Code : 

```
2025-01-18 20:03:35.974 [info] Checking herd PHP installation: herd which-php
2025-01-18 20:03:35.975 [info] Checking valet PHP installation: valet which-php
2025-01-18 20:03:35.975 [info] Checking local PHP installation: php -r 'echo PHP_BINARY;'
2025-01-18 20:03:35.975 [info] Checking sail PHP installation: ./vendor/bin/sail ps
2025-01-18 20:03:35.975 [info] Falling back to system PHP installation
2025-01-18 20:03:35.975 [error] Translation namespaces

Error: __VSCODE_LARAVEL_START_OUTPUT__
   BadMethodCallException 

  Method Illuminate\Filesystem\Filesystem::json does not exist.

  at D:\jipem\Sites\laragon\www\laravel\vendor\laravel\framework\src\Illuminate\Macroable\Traits\Macroable.php:113
    109▕      */
    110▕     public function __call($method, $parameters)
    111▕     {
    112▕         if (! static::hasMacro($method)) {
  ➜ 113▕             throw new BadMethodCallException(sprintf(
    114▕                 'Method %s::%s does not exist.', static::class, $method
    115▕             ));
    116▕         }
    117▕

  i   Bad Method Call: Did you mean Illuminate\Filesystem\Filesystem::extension() ? 

  1   D:\jipem\Sites\laragon\www\laravel\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:338
      Illuminate\Filesystem\Filesystem::__call("json")

  2   D:\jipem\Sites\laragon\www\laravel\vendor\_laravel_ide\discover-9bf70685f88c341f6dfa31892eff8be2.php:94
      Illuminate\Support\Facades\Facade::__callStatic("json")

2025-01-18 20:03:35.978 [info] Activating Laravel Extension...
2025-01-18 20:03:35.978 [info] Started
```

### Mimimal Code Sample

```php

```

**Comment by HassanZahirnia** [comment]
I'm also getting a similar error on WSL2 (Ubuntu)

![Image](https://github.com/user-attachments/assets/1f39df1e-3e02-4d60-a082-09f12955a700)

Version number is `0.1.18`

**Comment by patimio66** [comment]
Got similar error, Windows 11, latest.
![Image](https://github.com/user-attachments/assets/184c95d8-f341-4fd2-b214-5282486fe9ee)

Version number is `0.1.18`

**Comment by LukaszJaro** [comment]
Same error as @patimio66 running on windows 10. Just installed the extension today.

**Comment by slaanish** [comment]
Same issue as the others, Windows 11 WSL, Right clicking the extension and selecting 1.17 no longer errors.

![Image](https://github.com/user-attachments/assets/17d6707b-041b-468f-b50c-388467953dd9)

**Comment by slaanish** [comment]
Taking a look between 1.17 and 1.18, I do see there was a merge that did target language.  I do not even pretend to know what is going on, but it does touch language processing and happened between working version and now. All of us appear to be on Windows... A pathing issue?      \ vs /

https://github.com/laravel/vs-code-extension/commit/d0f299ce0fcfb0d2578571b71cc29eef96950a9c

**Comment by otavio-araujo** [comment]
Yep, it works!

**Comment by andreg** [comment]
I'm getting the same error as @patimio66, running on MacOS. Downgrading to 1.17 does apparently fix the issue though.

**Comment by Braunson** [comment]
Same issue on Windows in version `0.1.18`

**Comment by daronspence** [comment]
Can confirm this is still an issue on `0.1.18` on macOS. I tried running the generated vendor file directly with some more `dd()` statements and `try/catch` for good measure, but I couldn't trace it down.

Downgrading to version `0.1.17` at least stopped the extension from crashing. I was hoping that disabling the Translation options in the extension settings would skip the initialisation, but that seems to not be the case.

The JSON files are valid, though some strings do include HTML. Idk if that may be throwing off a parser somewhere?

**Comment by joetannenbaum** [comment]
I removed the `File::json` call from the translations repo in v0.1.19, just released. Does that solve this issue or is it still present in the latest version?

**Comment by mmuqiitf** [comment]
I hope this patch anytime soon because it's really annoying, i always click don't show again

![Image](https://github.com/user-attachments/assets/d36fe8a3-40cb-41b7-b476-7274dd5504e5)

**Comment by otavio-araujo** [comment]
Yep. The "safe" release is .17 for now...

Atenciosamente,

Otávio Araújo
________________________________
De: Mo Khosh ***@***.***>
Enviado: Wednesday, February 12, 2025 8:21:22 AM
Para: laravel/vs-code-extension ***@***.***>
Cc: Otávio Araújo ***@***.***>; Comment ***@***.***>
Assunto: Re: [laravel/vs-code-extension] [Bug]: "[error] Translation namespaces" (Issue #212)


Still getting it on .19

**Comment by joetannenbaum** [comment]
Would love to get to the bottom of this, I find it strange that you're getting JSON back but it's still erroring. Does anyone have a public repo I can pull down that replicates this?

**Comment by patimio66** [comment]
@joetannenbaum maybe it's related to VS Code locale? Like to the settings of VS code?

**Comment by priithansen** [comment]
My preliminary testing seems to suggest it's not a particular line or language file causing this error but the amount of translation strings. Seemed that there was a certain amount of lines needed (tested with validation translations) to cause this error to appear. Didn't seem matter which particular lines where present.

**Comment by joetannenbaum** [comment]
> My preliminary testing seems to suggest it's not a particular line or language file causing this error but the amount of translation strings. Seemed that there was a certain amount of lines needed (tested with validation translations) to cause this error to appear. Didn't seem matter which particular lines where present.

Yeah this is what I suspected. I'm tempted to add a setting to omit vendor translations, although I'd love to also have a solution to have them properly included as well. I'll continue investigating.

**Comment by duncanmcclean** [comment]
> Does anyone have a public repo I can pull down that replicates this?

We have _a lot_ of translation strings in our app/package (Statamic). I can see the error on any Statamic site I touch.

**Comment by joetannenbaum** [comment]
> > Does anyone have a public repo I can pull down that replicates this?
> 
> We have _a lot_ of translation strings in our app/package (Statamic). I can see the error on any Statamic site I touch.

Yup, seeing that too with a fresh install just now. Good place to start, thanks @duncanmcclean 👍

**Comment by joetannenbaum** [comment]
Just released v0.1.20 that should _greatly_ improve (if not fix) this issue. I completely overhauled the translations collection process and the performance + memory usage is much better now.

Let me know how it looks on your end!

**Comment by patimio66** [comment]
@joetannenbaum looks good on my side! Tried installing the extension from scratch, again, works fine on v0.1.20.

![Image](https://github.com/user-attachments/assets/d2363460-96cc-4d8f-bb72-503c35bd3306)

**Comment by slaanish** [comment]
Issues resolved for me as well, thanks!

**Comment by ghabriel25** [comment]
@joetannenbaum New error. I tried reinstall have the same error

![Image](https://github.com/user-attachments/assets/e0d60db9-38d9-46aa-afdc-4af524a4e7d9)

**Comment by mokhosh** [comment]
Resolved to me too. Thanks!

**Comment by sinchijackal** [comment]
Still getting it on 0.1.20 Windows 10 x64 bits version.

![Image](https://github.com/user-attachments/assets/ca8a2889-030e-4f03-a949-25c8d33329f2)

**Comment by JeremieMercier** [comment]
I still have this error too. Windows 11 24H2

![Image](https://github.com/user-attachments/assets/9812182c-3cf5-4bd3-b92b-bd7b5629f49f)

**Comment by ghabriel25** [comment]
> [@joetannenbaum](https://github.com/joetannenbaum) New error. I tried reinstall have the same error
> 
> ![Image](https://github.com/user-attachments/assets/e0d60db9-38d9-46aa-afdc-4af524a4e7d9)

Version 0.1.21 error fixed
![Image](https://github.com/user-attachments/assets/36936c3b-27d4-4662-ab5a-2e5c9e0f7b80)
