### ISSUE TITLE
[Bug]: Translation not found warning

### ISSUE THREAD

**Issue by Preslav-Stoyanov** [laravel/vs-code-extension#428]
### Extension Version

1.0.11

### PHP Binary

Local PHP

### Operating System

Linux

### What happened?

I tried to get translation array and it says it doesn't find it.
I still get the array with translations, but the extension shows an error and underlines the trans keys.

### Mimimal Code Sample

```php
//fields.php
return [
    'email' => 'Email',
    'name' => 'Name',
    'password' => 'Password',
];

// This works
trans('fields.email');
trans('fields.name');
trans('fields.password');

// This says Translation['fields'] not found.
trans('fields')
```

**Comment by N1ebieski** [comment]
https://github.com/laravel/vs-code-extension/pull/324

**Comment by TitasGailius** [comment]
Thanks for reporting this. We recently added some improvements to how translation detection works, so I’m hoping this is now fixed. Feel free to reopen the issue if you’re still running into problems.

**Comment by LukeSavefrogs** [comment]
@TitasGailius I still get the issue on version `2.0.0`:

```
Translation [navigation.groups.administration] not found.
Translation [navigation.groups.developer] not found.
```

Looking at the file:
```
sail@43332bb3f70b:/var/www/html$ cat lang/en/navigation.php 
<?php

return [
    "groups" => [
        "administration" => "Administration",
        "developer" => "Developer",
    ]
];
```
